# -*- coding: utf-8 -*-
"""Kovai.co.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EZy7S_G60CpTB19gPgcII2BBBiFEND4s
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/content/Daily_Public_Transport_Passenger_Journeys_by_Service_Type_20250603.csv")

df.head()

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

df.head()

#check for null values
df.isnull().sum()

""""Other" column alone have 20 missing values."""

df.describe()

df['Other'].fillna(df['Other'].mean(), inplace=True)

"""Replaced those missing values with the mean value."""

df = df.sort_values('Date')
df.head()

df['Total_Passengers'] = df[['Local Route','Light Rail','Peak Service','Rapid Route','School','Other']].sum(axis=1)
df.head()

"""Created a new key column — Total_Passengers, which will be used for trend analysis and forecasting.

"""

plt.figure(figsize=(30,6))
plt.plot(df['Date'], df['Total_Passengers'], color='blue')
plt.title("Daily Public Transport Passenger Trend")
plt.xlabel("Date")
plt.ylabel("Total Passengers")
plt.grid(True)
plt.show()

"""It seems to have some trend in the data.Total passenger numbers increasing over time.Noticeable dips likely weekends, holidays, or lockdown periods"""

df['Rolling_7'] = df['Total_Passengers'].rolling(7).mean()
df['Rolling_30'] = df['Total_Passengers'].rolling(30).mean()
plt.figure(figsize=(30,6))
plt.plot(df['Date'], df['Total_Passengers'], label='Actual', alpha=0.5)
plt.plot(df['Date'], df['Rolling_7'], label='7-day Average', color='red')
plt.plot(df['Date'], df['Rolling_30'], label='30-day Average', color='green')
plt.legend()
plt.title("Passenger Trends with Rolling Averages")
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt

df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date')

# Setting Date as index (required for decomposition)
df.set_index('Date', inplace=True)

# Applying seasonal decomposition
decomposition = seasonal_decompose(df['Total_Passengers'], model='additive', period=7)  # 7 for weekly pattern

# Plot the decomposition
plt.rcParams.update({'figure.figsize': (12,8)})
decomposition.plot()
plt.suptitle("Time Series Decomposition: Trend, Seasonality, Residual", fontsize=14)
plt.show()

"""The Augmented Dickey-Fuller (ADF) Test checks whether our data is stationary (no trend/seasonality).
Most time-series forecasting models (like ARIMA) need stationary data. Prophet can handle non-stationary data.
"""

from statsmodels.tsa.stattools import adfuller

# Run ADF test
result = adfuller(df['Total_Passengers'])

print("ADF Statistic:", result[0])
print("p-value:", result[1])
print("Critical Values:")
for key, value in result[4].items():
    print(f"\t{key}: {value}")

if result[1] < 0.05:
    print("\n The series is stationary (no significant trend/seasonality).")
else:
    print("\n The series is NOT stationary (has trend or seasonality).")

"""The test statistics should be less than the critical values.The p-value is less than 0.5.

The ADF test confirmed the data is stationary — suitable for ARIMA modeling.

p-value = 0.00043 (Stationary).So no differencing is needed.Hence,d = 0.We use two diagnostic plots to determine p and q:
ACF (Autocorrelation Function) - helps choose q
PACF (Partial Autocorrelation Function) -helps choose p
"""

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
plt.subplot(1,2,1)
plot_acf(df['Total_Passengers'], ax=plt.gca(), lags=30)
plt.title("ACF Plot (For MA - q)")

plt.subplot(1,2,2)
plot_pacf(df['Total_Passengers'], ax=plt.gca(), lags=30)
plt.title("PACF Plot (For AR - p)")

plt.show()

"""both cut off around lag 2.so,
(p, d, q) = (2, 0, 2)
"""

for p in range(0, 3):
    for q in range(0, 3):
        try:
            model = ARIMA(df['Total_Passengers'], order=(p, 0, q))
            results = model.fit()
            print(f"ARIMA({p},0,{q}) -> AIC: {results.aic}")
        except:
            continue

"""ARIMA(0,0,2) has lowest value."""

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
import warnings
warnings.filterwarnings("ignore")

# TO Ensure 'Date' column is datetime and sorted
df = df.reset_index()
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date')
df.set_index('Date', inplace=True)

#ARIMA model
model = ARIMA(df['Total_Passengers'], order=(0,0,2))
results = model.fit()

print(results.summary())

forecast_steps = 730
forecast = results.forecast(steps=forecast_steps)

# Create forecast dates
forecast_dates = pd.date_range(df.index[-1], periods=forecast_steps + 1, freq='D')[1:]


plt.figure(figsize=(30,6))
plt.plot(df['Total_Passengers'], label='Actual')
plt.plot(forecast_dates, forecast, label='Forecast', color='red')
plt.title("ARIMA Forecast of Daily Passenger Journeys")
plt.xlabel("Date")
plt.ylabel("Total Passengers")
plt.legend()
plt.grid(True)
plt.show()

train_size = int(len(df) * 0.8)
train, test = df['Total_Passengers'][:train_size], df['Total_Passengers'][train_size:]

model_eval = ARIMA(train, order=(2,0,2))
result_eval = model_eval.fit()
forecast_eval = result_eval.forecast(steps=len(test))

# Evaluation metrics
mae = mean_absolute_error(test, forecast_eval)
rmse = np.sqrt(mean_squared_error(test, forecast_eval))

print("Mean Absolute Error (MAE):", mae)
print("Root Mean Squared Error (RMSE):", rmse)

# Plot comparison
plt.figure(figsize=(12,6))
plt.plot(test.index, test, label='Actual', color='blue')
plt.plot(test.index, forecast_eval, label='Predicted', color='red')
plt.title("Actual vs Predicted Passenger Counts")
plt.xlabel("Date")
plt.ylabel("Total Passengers")
plt.legend()
plt.grid(True)
plt.show()

"""Still has some Errors.We will try doing with SARIMA modoel as it works well for Seasonality."""

# Try nearby models
for order in [(0,0,1), (1,0,1), (1,0,2), (2,0,2)]:
    model = ARIMA(df['Total_Passengers'], order=order)
    results = model.fit()
    print(f"ARIMA{order} -> AIC: {results.aic}")

from statsmodels.tsa.statespace.sarimax import SARIMAX

model = SARIMAX(df['Total_Passengers'], order=(0,0,2), seasonal_order=(1,1,1,7))  # 7 = weekly seasonality
results = model.fit()
print(results.summary())

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Assuming your df already has 'Date' as index and 'Total_Passengers' column
df = df.asfreq('D')  # Ensure daily frequency

# Fill missing values if any
df['Total_Passengers'].fillna(method='ffill', inplace=True)

train = df.iloc[:-30]
test = df.iloc[-30:]

model = SARIMAX(train['Total_Passengers'],
                order=(2,0,2),
                seasonal_order=(1,1,1,7))   # weekly pattern
results = model.fit(disp=False)

pred = results.get_forecast(steps=30)
pred_mean = pred.predicted_mean
pred_ci = pred.conf_int()

plt.figure(figsize=(40,10))
plt.plot(train.index, train['Total_Passengers'], label='Train', color='blue')
plt.plot(test.index, test['Total_Passengers'], label='Test', color='green')
plt.plot(pred_mean.index, pred_mean, label='Forecast', color='red')
plt.fill_between(pred_ci.index, pred_ci.iloc[:,0], pred_ci.iloc[:,1], color='pink', alpha=0.3)
plt.title("SARIMA Forecast vs Actuals")
plt.xlabel("Date")
plt.ylabel("Passengers")
plt.legend()
plt.show()

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(test['Total_Passengers'], pred_mean)
rmse = np.sqrt(mean_squared_error(test['Total_Passengers'], pred_mean))

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")

"""I tested both ARIMA and SARIMA models to forecast daily public transport passenger journeys.
After testing various parameters, ARIMA(2,0,2) gave a baseline MAE of 17,023.
However, when I included weekly seasonality using SARIMA(2,0,2)(1,1,1,7),
the MAE improved to 13,331 — indicating that the dataset has a weekly seasonal trend (likely weekday vs weekend passenger differences).
Hence, SARIMA is the more suitable model for this dataset
"""

df = df[['Local Route','Light Rail','Peak Service','Rapid Route','School']]

# WEEKLY SEASONALITY DETECTION
df_weekly = df.resample('W').sum()
plt.figure(figsize=(10,5))
plt.plot(df_weekly['Local Route'], label='Local Route', color='blue')
plt.title("Weekly Passenger Pattern - Local Route")
plt.xlabel("Week")
plt.ylabel("Passengers")
plt.legend()
plt.show()

#  TREND DETECTION (MOVING AVERAGE)
df['LocalRoute_Trend'] = df['Local Route'].rolling(window=30).mean()

plt.figure(figsize=(10,5))
plt.plot(df['Local Route'], color='lightgray', label='Original')
plt.plot(df['LocalRoute_Trend'], color='red', label='30-Day Moving Average')
plt.title("Growth Trend in Local Route Usage")
plt.legend()
plt.show()

#  SERVICE TYPE COMPARISON
plt.figure(figsize=(20,5))
sns.lineplot(data=df[['Local Route','Light Rail','Rapid Route','School']])
plt.title("Service Type Comparison Over Time")
plt.ylabel("Passenger Count")
plt.show()

# DETECT COVID OR EVENT SPIKES
plt.figure(figsize=(10,5))
plt.plot(df['Local Route'], color='purple')
plt.title("Event or Holiday Spikes - Local Route")
plt.ylabel("Passengers")
plt.show()

"""Sudden dips or spikes in the line may indicate holidays or disruptions."""

# CORRELATION BETWEEN SERVICE TYPES
corr_matrix = df[['Local Route','Light Rail','Peak Service','Rapid Route','School']].corr()

plt.figure(figsize=(6,4))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Between Service Types")
plt.show()

"""Task 1:
4to 5 Key Insights:
1.Weekly Seasonality Detected:
   Passenger count shows a clear weekly pattern — peaks on weekdays and dips on weekends.
2.Service Type Comparison:
   - Local Route contributes the highest number of daily passengers.  
   - Light Rail and Rapid Route have steady but lower volumes.  
   - School category peaks only during school months.
  3.COVID/Post-COVID Recovery or Event Spikes:
   The dataset shows occasional dips/spikes, which may be due to external factors like holidays or public events.
   4.Correlation Between Service Types:
   Services like Local Route and Peak Service are positively correlated — when general passengers increase, peak-hour usage also rises.
   5.Growth Trend in Public Transport Usage:
   Overall passenger journeys have a gradual upward trend, indicating increased public transport usage over time.

FORECASTING OF LOCAL ROUTE,LIGHT RAIL,PEAK SERVICE,RAPID ROUTE,SCHOOL FOR THE NEXT 7 DAYS.
"""

from statsmodels.tsa.statespace.sarimax import SARIMAX
import matplotlib.pyplot as plt

forecast_results = {}

for column in ['Local Route', 'Light Rail', 'Peak Service', 'Rapid Route', 'School']:
    print(f"\n🔹 Forecasting for: {column}")
    df_column = df[[column]].asfreq('D')
    df_column[column].fillna(method='ffill', inplace=True)

    # Train-Test Split (keep last 7 days for test)
    train = df_column.iloc[:-7]
    test = df_column.iloc[-7:]

    # Fit SARIMA
    model = SARIMAX(train[column],
                    order=(2,0,2),
                    seasonal_order=(1,1,1,7),
                    enforce_stationarity=False,
                    enforce_invertibility=False)
    results = model.fit(disp=False)

    # Forecast next 7 days
    forecast = results.get_forecast(steps=7)
    forecast_mean = forecast.predicted_mean
    forecast_ci = forecast.conf_int()

    # Store results
    forecast_results[column] = forecast_mean

    # Plot forecast
    plt.figure(figsize=(10,5))
    plt.plot(train.index, train[column], label='Train', color='blue')
    plt.plot(test.index, test[column], label='Actual', color='green')
    plt.plot(forecast_mean.index, forecast_mean, label='Forecast', color='red')
    plt.fill_between(forecast_ci.index, forecast_ci.iloc[:,0], forecast_ci.iloc[:,1], color='pink', alpha=0.3)
    plt.title(f"7-Day Forecast for {column}")
    plt.legend()
    plt.show()

# Combine all forecast results
forecast_df = pd.DataFrame(forecast_results)
forecast_df

